version: '3'

services:
  postgres:
    image: postgres:12
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 54320:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ['start-dev']
    container_name: keycloak
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KEYCLOAK_SSL_REQUIRED=none
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KC_BOOTSTRAP_ADMIN_USERNAME=superadmin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=userpass
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - 1080:8080
      - 1443:8443
    depends_on:
      - postgres
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge
